### ISSUE TITLE
Add a "draw" method to dl which draws an Array3D to a canvas.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#611] opened 2018-01-28 17:51 UTC
In at least 5 demos, we have this block copied: 
```
const imageData = ctx.createImageData(IMAGE_SIZE, IMAGE_SIZE);

let pixelOffset = 0;
for (let i = 0; i < values.length; i++) {
  const value = values[i];
  imageData.data[pixelOffset++] = value;
  imageData.data[pixelOffset++] = value;
  imageData.data[pixelOffset++] = value;
  imageData.data[pixelOffset++] = 255;
}

ctx.putImageData(imageData, 0, 0);
```

Let's move this to a method "draw" or possibly "imshow".

**Comment by dsmilkov** [comment] 2018-02-19 15:07
Duplicate of #751

**Closed by dsmilkov** 2018-02-19 15:07 UTC
Labels: P2
