### ISSUE TITLE
Add functionality for SVD.

### ISSUE THREAD

**Issue by nsthorat** [PAIR-code/deeplearnjs#245] opened 2017-10-19 17:56 UTC
We can add this under a `linalg` file, just like numpy does.

See: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.svd.html

**Comment by haasdo95** [comment] 2018-01-21 02:04
I'd like to have a try on this one...
But I'll have to review my numerical methods a little bit...

**Comment by dsmilkov** [comment] 2018-01-21 04:56
Duplicate of #571

**Closed by dsmilkov** 2018-01-21 04:56 UTC
Labels: help wanted
